export const _urlBase = "http://10.20.30.30"
export const _APIEstable = ":8000"
export const _tasksPath = "/task/all"
export const _transcriptPath = "/task"
export const _APICanary = ":7000"
export const _recordsPath = "/records/all"
export const _urlCanary = "http://10.20.30.106"
